// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Module 1 sidebar
  module1Sidebar: [
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        'module1-ros2/introduction-to-ros2',
        'module1-ros2/ros2-communication-primitives',
        'module1-ros2/urdf-humanoid-representation',
      ],
    },
  ],

  // Module 2 sidebar
  module2Sidebar: [
    {
      type: 'category',
      label: 'Module 2: Simulation and Digital Twin Concepts',
      items: [
        'module2-simulation/simulation-fundamentals',
        'module2-simulation/gazebo-robotics-simulation',
        'module2-simulation/unity-digital-twin-applications',
      ],
    },
  ],

  // Module 3 sidebar
  module3Sidebar: [
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac™)',
      items: [
        'module3-ai-robot-brain/introduction-to-nvidia-isaac',
        'module3-ai-robot-brain/isaac-sim-advanced-simulation',
        'module3-ai-robot-brain/isaac-ros-nav2-navigation',
      ],
    },
  ],

  // Module 4 sidebar
  module4Sidebar: [
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        'module4-vla/vla-fundamentals-introduction',
        'module4-vla/voice-to-action-llm-planning',
        'module4-vla/capstone-autonomous-humanoid',
      ],
    },
  ],
};

export default sidebars;


