"""Data models for the embeddings generation service."""

from dataclasses import dataclass
from typing import Optional, Dict, Any
from datetime import datetime


@dataclass
class BookContent:
    """The source text from books that will be processed into embeddings."""

    id: str
    url: str
    title: str
    content: str
    content_type: str
    created_at: datetime
    updated_at: datetime


@dataclass
class ContentChunk:
    """A processed chunk of book content that will be converted to embeddings."""

    id: str
    book_content_id: str
    text: str
    chunk_index: int
    word_count: int
    metadata: Optional[Dict[str, Any]] = None


@dataclass
class Embedding:
    """Vector representation of text content generated by Cohere model."""

    id: str
    chunk_id: str
    vector: list
    vector_size: int
    model_name: str
    created_at: datetime


@dataclass
class QdrantRecord:
    """Database entry in Qdrant containing embeddings with metadata."""

    id: str
    vector: list
    payload: Dict[str, Any]
    collection_name: str


@dataclass
class ProcessingJob:
    """Track the status of embedding generation jobs."""

    id: str
    status: str  # pending, processing, completed, failed
    source_url: str
    total_chunks: int
    processed_chunks: int
    created_at: datetime
    completed_at: Optional[datetime] = None
    error_message: Optional[str] = None